### ISSUE TITLE
Tested a few more demos

### ISSUE THREAD

**Issue by zonaj** [polpo/picogus#1]
I've tested a few unverified demos.

Seem perfect:
- Stash by The Black Lotus
- Fluid Motion by Valhalla
- Heartquake by Iguana
- DX Project by RealTech
- My Summer Demo by Byterapers
- Solstice by Valhalla
- Caero by Plant and EMF
- Aquaphobia by RealTech
- Contrast by Oxygene
- Machines of Madness by Cubic Team
- Lasse Reinbøng by Cubic Team & $eeN
- Genocyd by GMF
- Mindtrap by Trauma
- Jizz by The Black Lotus
- Robotnik by Rage
- Boost by Doomsday

Imperfect:
- Disgust by Camorra (credits at the end have strange timing)

Possibly problematic (I did not try very hard to run them):
- Sunflower by Pulse (hangs at the beginning)
- Pump by Iguana (hangs in the middle)

**Comment by polpo** [comment]
Thank you for all of the results! I will add them to the compatibility list.

**Comment by polpo** [comment]
I'm happy to report that Sunflower by Pulse runs perfectly now with my latest firmware that I will be releasing soon 😀

**Comment by polpo** [comment]
The compatibility list has been updated with these demos. Thanks again for opening this issue!

**Comment by zonaj** [comment]
Very cool, I confirm that sunflower works with the latest firmware! Same thing with "Pump" by iguana. Works great now.
