### ISSUE TITLE
PGUSINIT Usage is wrong

### ISSUE THREAD

**Issue by SuperIlu** [polpo/picogus#5]
The usage specifies "/b" as option to set the base address, the option parsing uses "/p" to scanf() `port_override`

**Comment by SuperIlu** [comment]
Also, I just noticed:
`/d n - force DMA interval to n æs. Default: 0, Min: 1, Max: 256`

default is 0, but minimum value is 1?

and isn't the value an uint8_t? Wouldn't that make the max:=255 (same for sample buffer size)?

**Comment by arkayii** [comment]
Since we're talking about this area, I'll mention this very minor, errr, quibble. As the MS-DOS environment is typically non case-sensitive, it might be appropriate to allow/parse switch parameters in both upper and lower case.

**Comment by SuperIlu** [comment]
submitted a PR for this #6
