### ISSUE TITLE
Can't init femto with ISA adapter

### ISSUE THREAD

**Issue by kp73** [polpo/picogus#53]
Hi, trying to init and get an error;

`ERROR: PicoGUS card using protocal 221, needs 2`

Using a femto with ISA adapter from Tindie https://www.tindie.com/products/polpo/picogus-femto-edition-for-pocket-386-and-isa/

Programmed the Pico by holding BOOTSEL and dropping pg-gus.uf2 from picogus-v1.2.0 release (unplugged from femto).  

Stuck it in my 486 using the ISA adapter, but no joy.  Will try it in the book 8088 when I find the power adapter :)

A standard PicoGUS v2 works fine in the 486

![IMG_6363](https://github.com/polpo/picogus/assets/7387948/0981b563-28e9-4efa-8cf6-88b8940020e6)

**Comment by kp73** [comment]
Seems to work OK on the book808 

![IMG_6364](https://github.com/polpo/picogus/assets/7387948/0c0c83f5-60fb-4516-9baf-58c75adf315e)

Any idea why it won't work with the ISA adapter?

**Comment by polpo** [comment]
Hi, sorry for the delay in getting back to you. There are probably solder bridges on the ISA adapter on the fine pitched pin connector that the Femto plugs into. Take a close look, if you are handy with soldering you can clean any bridges up with some flux or solder braid. If not I can send you a new one - send me a message on Tindie and I'll take care of you.
